name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy --no-default-features
        run: cargo clippy --no-default-features -- -D warnings

      - name: Clippy -- default
        run: cargo clippy --features=default -- -D warnings

      - name: Clippy --all-features
        run: cargo clippy --all --all-features -- -D warnings

      - name: Clippy -- tokio
        run: cargo clippy --no-default-features --features=tokio -- -D warnings

      - name: Clippy -- cody-c
        run: cargo clippy --no-default-features --features=cody-c -- -D warnings
        
      - name: Test
        run: cargo test --all --all-features
